### ISSUE TITLE
Разница между crud.select и box.select

### ISSUE THREAD

**Issue by Bl4ugrane** [peneksglazami/tarantool-cartridge-webinar#1]
По вашему примеру развернул в докере кластер, но столкнулся с одной проблемой: после запуска миграций я подключаюсь к консоли одного из контейнеров и сначала выполняю команду  crud.select("space_name",{}), которая мне выводит все записи по спейсу, как и ожидается. Затем выполняю команду box.space.space_name:select{}, которая выводит мне только часть записей в спейсе.  Может знаете почему такое поведение у этих одинаковых команд?

**Comment by peneksglazami** [comment]
@Bl4ugrane, модуль crud рассматривает кластер, созданный Tarantool Cartridge, как единое пространство. То есть фактически вызов команды crud.select на одном из узлов Tarantool, приведёт к тому, что запросы будут отправлены на все узлы Tarantool, где присутствует данный спейс. Таким образом, данные будут собраны со всего кластера. Команда box.space.space_name:select{} в свою очередь ничего не знает про другие узлы кластера и выполнит выборку данных только с данного узла. Соответственно, в результат выборки попадут только те записи, который алгоритмом шардирования были отнесены для хранения на данный узел.

Вот тут есть описание того, как работает crud.select - https://github.com/tarantool/crud/blob/master/doc/select.md
