### ISSUE TITLE
Можно ли использовать SQL запрос в функциях модуля vshard?

### ISSUE THREAD

**Issue by Bl4ugrane** [peneksglazami/tarantool-cartridge-webinar#2]
Добрый день!
Можно ли при использовании функции vshard.router.callrw() или vshard.router.callro() передать функцию например box.execute('select * from table;') ?

**Comment by peneksglazami** [comment]
@Bl4ugrane, вызвать можно в принципе любую функцию. Выполнение SQL-запросы будет выглядеть так
`vshard.router.callbro(bucket_id, 'box.execute', {'select * from "users"'} )`

**Comment by Bl4ugrane** [comment]
Спасибо!
